[workspace]
members = ["selene", "selene-lib"]

[workspace.package]
version = "0.23.1"
authors = ["Kampfkarren <kampfkarren@gmail.com>"]
edition = "2021"
homepage = "https://kampfkarren.github.io/selene/"
license = "MPL-2.0"
repository = "https://github.com/Kampfkarren/selene"

[workspace.dependencies]
dirs = "4.0.0"

full_moon = { git = "https://github.com/Kampfkarren/full-moon", branch = "lua-types" }
# full_moon = { path = "../full-moon/full-moon" }

full-moon-lua-types = { git = "https://github.com/Kampfkarren/full-moon", branch = "lua-types" }
# full-moon-lua-types = { path = "../full-moon/full-moon-lua-types" }
