[package]
name = "selene-lib"
version = "0.21.1"
license = "MPL-2.0"
authors = ["Kampfkarren <kampfkarren@gmail.com>"]
description = "A library for linting Lua code. You probably want selene instead."
categories = ["command-line-utilities"]
keywords = ["lua", "linter", "lua51"]
repository = "https://github.com/Kampfkarren/selene"
edition = "2021"

[dependencies]
codespan = "0.9"
codespan-reporting = "0.9"
full_moon = "0.15.1"
id-arena = "2.2"
if_chain = "1.0.2"
lazy_static = "1.4"
once_cell = "1.12.0"
paste = "1.0.9"
profiling = "1.0.6"
regex = "1.6.0"
serde = "1.0.144"
serde_yaml = "0.8.24"
toml = "0.5.9"

[dev-dependencies]
serde_json = "1.0"
pretty_assertions = "0.6"
termcolor = "1.0"

[features]
default = ["roblox"]
force_exhaustive_checks = []
roblox = ["full_moon/roblox"]
