[package]
name = "selene-lib"
version = "0.10.1"
license = "MPL-2.0"
authors = ["Kampfkarren <kampfkarren@gmail.com>"]
description = "A library for linting Lua code. You probably want selene instead."
categories = ["command-line-utilities"]
keywords = ["lua", "linter", "lua51"]
repository = "https://github.com/Kampfkarren/selene"
edition = "2018"

[dependencies]
codespan = "0.9"
codespan-reporting = "0.9"
full_moon = "0.9"
id-arena = "2.2"
if_chain = "1.0"
lazy_static = "1.4"
paste = "1.0"
rbx_reflection = { version = "3", optional = true }
regex = "1"
serde = "1.0"
toml = "0.5"

[dev-dependencies]
serde_json = "1.0"
pretty_assertions = "0.6"
termcolor = "1.0"

[features]
default = ["roblox"]
roblox = ["rbx_reflection", "full_moon/roblox"]