[luacheck2]
base = "lua51"

[luacheck2.structs.EnumItem.Name]
property = true

[luacheck2.structs.EnumItem.Value]
property = true

[luacheck2.structs.Instance."*"]
any = true

[[CFrame.Angles.args]]
type = "number"
required = false

[[CFrame.Angles.args]]
type = "number"
required = false

[[CFrame.Angles.args]]
type = "number"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[CFrame.new.args]]
type = "any"
required = false

[[Color3.fromRGB.args]]
type = "number"

[[Color3.fromRGB.args]]
type = "number"

[[Color3.fromRGB.args]]
type = "number"

[[Color3.new.args]]
type = "number"
required = false

[[Color3.new.args]]
type = "number"
required = false

[[Color3.new.args]]
type = "number"
required = false

[[delay.args]]
type = "number"

[[delay.args]]
type = "function"

# TODO: Constant type
[[Instance.new.args]]
type = "string"

[[Ray.new.args]]
type = { display = "Vector3" }

[[Ray.new.args]]
type = { display = "Vector3" }

[[Rect.new.args]]
type = "any"

[[Rect.new.args]]
type = "any"

[[Rect.new.args]]
type = "any"
required = false

[[Rect.new.args]]
type = "any"
required = false

[settings]
args = []

[[spawn.args]]
type = "function"

[tick]
args = []

[time]
args = []

[[TweenInfo.new.args]]
type = "number"
required = false

[[TweenInfo.new.args]]
type = { display = "EasingStyle" }
required = false

[[TweenInfo.new.args]]
type = { display = "EasingDirection" }
required = false

[[TweenInfo.new.args]]
type = "number"
required = false

[[TweenInfo.new.args]]
type = "bool"
required = false

[[TweenInfo.new.args]]
type = "number"
required = false

[[typeof.args]]
type = "any"

[[UDim.new.args]]
type = "number"

[[UDim.new.args]]
type = "number"

[[UDim2.new.args]]
type = "any"

[[UDim2.new.args]]
type = "any"

[[UDim2.new.args]]
type = "any"
required = false

[[UDim2.new.args]]
type = "any"
required = false

[[Vector2.new.args]]
type = "number"
required = false

[[Vector2.new.args]]
type = "number"
required = false

[[Vector3.new.args]]
type = "number"
required = false

[[Vector3.new.args]]
type = "number"
required = false

[[Vector3.new.args]]
type = "number"
required = false

[[warn.args]]
type = "string"

[[warn.args]]
type = "..."
required = false

[[wait.args]]
type = "number"
required = false
