[package]
name = "generate-roblox-std"
version = "0.1.0"
license = "MPL-2.0"
authors = ["Kampfkarren <boynedmaster@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
luacheck2-lib = { path = "../luacheck2-lib" }
reqwest = "0.9"
serde = "1.0"
toml = "0.5"
