[package]
name = "selene"
version = "0.1.0"
license = "MPL-2.0"
authors = ["Kampfkarren <kampfkarren@gmail.com>"]
edition = "2018"

[dependencies]
codespan = "0.4"
codespan-reporting = "0.4"
full_moon = "0.4.0-rc.11"
lazy_static = "1.4"
glob = "0.3"
selene-lib = { path = "../selene-lib" }
num_cpus = "1.10"
structopt = "0.3"
termcolor = "1.0"
threadpool = "1.7"
toml = "0.5"

[features]
roblox = ["selene-lib/roblox"]