[package]
name = "selene"
version = "0.5.3"
license = "MPL-2.0"
authors = ["Kampfkarren <kampfkarren@gmail.com>"]
description = "A blazing-fast modern Lua linter written in Rust"
categories = ["command-line-utilities"]
keywords = ["lua", "linter", "lua51"]
repository = "https://github.com/Kampfkarren/selene"
documentation = "https://kampfkarren.github.io/selene/"
edition = "2018"

[dependencies]
atty = "0.2"
cfg-if = "0.1"
codespan = { version = "0.4", features = ["serialization"] }
codespan-reporting = { version = "0.4", features = ["serialization"] }
full_moon = "=0.4.0-rc.14"
lazy_static = "1.4"
glob = "0.3"
num_cpus = "1.10"
reqwest = { version = "0.9", optional = true }
selene-lib = { path = "../selene-lib", version = "0.5.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
termcolor = "1.0"
threadpool = "1.7"
toml = "0.5"
chrono = "0.4"

[features]
default = ["roblox"]
roblox = ["selene-lib/roblox", "full_moon/roblox", "reqwest"]
