[book]
authors = ["Kampfkarren"]
language = "en"
multilingual = false
src = "src"
title = "selene Documentation"

[output.html.redirect]
"/cli/configuration.html" = "/usage/configuration.html"
"/cli/std.html" = "/usage/std.html"