name: Build selene
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build (All features)
      run: |
        cd selene
        cargo build --locked --release --all-features
        New-Item release -ItemType "directory"
        Move-Item ..\target\release\selene.exe .\release\selene.exe
    - name: Build (Lightweight)
      run: |
        cd selene
        cargo build --locked --release --verbose --no-default-features
        Move-Item ..\target\release\selene.exe .\release\selene-light.exe
    - name: Upload selene
      uses: actions/upload-artifact@v1
      with:
        name: selene-windows
        path: ./selene/release/selene.exe
    - name: Upload selene-light
      uses: actions/upload-artifact@v1
      with:
        name: selene-light-windows
        path: ./selene/release/selene-light.exe
  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Build (All features)
      run: |
        source $HOME/.cargo/env
        cd selene
        cargo build --locked --release --all-features
        mkdir release/
        mv ../target/release/selene ./release/selene
    - name: Build (Lightweight)
      run: |
        source $HOME/.cargo/env
        cd selene
        cargo build --locked --release --verbose --no-default-features
        mv ../target/release/selene ./release/selene-light
    - name: Upload selene
      uses: actions/upload-artifact@v1
      with:
        name: selene-macos
        path: ./selene/release/selene
    - name: Upload selene-light
      uses: actions/upload-artifact@v1
      with:
        name: selene-light-macos
        path: ./selene/release/selene-light
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build (All features)
      run: |
        cd selene
        cargo build --locked --release --all-features
        mkdir release/
        mv ../target/release/selene ./release/selene
    - name: Build (Lightweight)
      run: |
        cd selene
        cargo build --locked --release --verbose --no-default-features
        mv ../target/release/selene ./release/selene-light
    - name: Upload selene
      uses: actions/upload-artifact@v1
      with:
        name: selene-linux
        path: ./selene/release/selene
    - name: Upload selene-light
      uses: actions/upload-artifact@v1
      with:
        name: selene-light-linux
        path: ./selene/release/selene-light