name: Deploy
# on:
#   release:
#     types: [created]
on: [push]

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
    - name: Install mdBook
      run: cargo install mdbook --vers "^0.3.0"
    - uses: actions/checkout@v1
    - name: Create Worktree
      run: git worktree add /tmp/book gh-pages
    - name: Build docs
      run: mdbook build docs
    - name: Commit files
      run: |
        rm -rf /tmp/book/*
        cp -rp docs/book/* /tmp/book/
        cd /tmp/book
        git add -A
        git config --global user.email "boynedmaster@gmail.com"
        git config --global user.name "Kampfkarren"
        git commit -m "Update book"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages