name: Generate Roblox standard library
on: [push, pull_request]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate
      run: cargo run --bin selene --verbose -- generate-roblox-std
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: roblox
        path: roblox.toml