name: Test selene
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: test-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - name: Run tests (selene, all features)
      run: cargo test
      working-directory: selene
    - name: Run tests (selene, no features)
      run: cargo test --no-default-features
      working-directory: selene
    - name: Run tests (selene-lib, all features)
      run: cargo test
      working-directory: selene-lib
    - name: Run tests (selene-lib, no features)
      run: cargo test --no-default-features
      working-directory: selene-lib
  # Remove this when non_exhaustive_omitted_patterns_lint is made stable in the next Rust version
  test_exhaustive_checks:
    runs-on: ubuntu-latest
    concurrency:
      group: test_exhaustive_checks-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v1
    - name: Install nightly for exhaustive check tests
      uses: dtolnay/rust-toolchain@nightly
    - name: Run exhaustive check tests
      run: cargo check --features force_exhaustive_checks
      working-directory: selene-lib
  alternate_tests:
    runs-on: ubuntu-latest
    concurrency:
      group: alternate_tests-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Run clippy
        run: cargo clippy -- -D warnings
        if: always()
      - name: Rustfmt
        run: cargo fmt -- --check
        if: always()
      - name: Run integration tests
        run: chmod +x ./run_tests.sh; ./run_tests.sh
        working-directory: selene-integration-tests/
        if: always()
